Repository jphacks/kz_2404, pull requests merged in 2024-11, with the labels that each got.

#59 ワークフロー作成
  .github/workflows/ai-review.yml
Labels: Review effort [1-5]: 2

#63 レビューAIのモデルの修正
  .github/workflows/ai-review.yml
Labels: Review effort [1-5]: 1

#61 フロント→バックエンド画像アップロードリファクタリング
  app/package-lock.json
  app/package.json
  app/src/app/api/minio/route.ts
  app/src/app/camera/page.tsx
Labels: Review effort [1-5]: 3

#62 ユーザーページのリファクタリング
  app/src/app/user/page.tsx
  app/src/components/ui/progress.tsx
  app/src/components/ui/slider.tsx
  app/src/components/view/user/StatusChangeDialog.tsx
  app/src/components/view/user/StatusList.tsx
Labels: Review effort [1-5]: 3

#65 ユーザーページにランクを表示するコンポーネントを作成
  app/src/app/user/page.tsx
  app/src/components/view/user/PlayerRankCard.tsx
Labels: Review effort [1-5]: 3

#64 スコア算出のリファクタリング
  app/src/app/api/minio/route.ts
  app/src/functions/scoreRegister.ts
Labels: Review effort [1-5]: 3

#66 ユーザーデータの型変更
  app/src/app/camera/page.tsx
  app/src/app/page.tsx
  app/src/app/user/page.tsx
  app/src/lib/signInAndUp.ts
Labels: Review effort [1-5]: 4

#70 課題ある時のみカメラオンにするように修正
  app/src/app/camera/page.tsx
  app/src/components/AssignmentBadge.tsx
Labels: Review effort [1-5]: 3

#67 トーストの位置変更
  app/src/app/camera/page.tsx
Labels: Review effort [1-5]: 2

#71 aタグをLinkを使用した遷移に修正
  app/src/components/layout/footer.tsx
Labels: Review effort [1-5]: 2

#68 rate shema, userRate shema, API の作成
  app/prisma/schema.prisma
  app/prisma/seed.ts
  app/src/app/api/rate/user/[id]/route.ts
  app/src/app/api/user/new/route.ts
  compose.yml
Labels: Review effort [1-5]: 4

#72 メール送信&課題作成API
  app/src/app/api/mailer/assginment/route.ts
Labels: Review effort [1-5]: 4

#69 ステータス調整のAPI繋ぎ込み＆ダイアログの修正
  app/package-lock.json
  app/src/app/api/experiencePoint/me/[id]/route.ts
  app/src/app/api/experiencePoint/status/[id]/route.ts
  app/src/app/camera/page.tsx
  app/src/app/page.tsx
  app/src/app/ranking/page.tsx
  app/src/app/user/page.tsx
  app/src/components/view/LoadingSpinner.tsx
  app/src/components/view/PointDialog.tsx
  app/src/components/view/ranking/ImageList.tsx
  app/src/components/view/ranking/RankingListAll.tsx
  app/src/components/view/ranking/RankingListToday.tsx
  app/src/components/view/ranking/RankingListWeekly.tsx
  app/src/components/view/user/PlayerRankCard.tsx
  app/src/components/view/user/StatusChangeDialog.tsx
  app/src/components/view/user/StatusList.tsx
  app/src/lib/atom.ts
  app/src/types/index.tsx
Labels: Review effort [1-5]: 4

#73 ログアウトボタンとメール通知の切り替えボタン&APIを追加
  app/prisma/schema.prisma
  app/src/app/api/mailer/route.ts
  app/src/app/api/user/updateReceivedMail/route.ts
  app/src/app/user/page.tsx
  app/src/lib/signInAndUp.ts
Labels: Review effort [1-5]: 4

#75 サインアップ後にログインされるように修正
  app/src/app/camera/page.tsx
  app/src/lib/signInAndUp.ts
Labels: Review effort [1-5]: 3

#77 footerのCSSを修正
  app/src/components/layout/footer.tsx
Labels: Review effort [1-5]: 2

#79 フラグでメール送信
  app/src/app/api/mailer/assginment/route.ts
Labels: Review effort [1-5]: 2

#81 各ページのCSSを調整
  app/src/app/page.tsx
  app/src/app/ranking/page.tsx
  app/src/app/user/page.tsx
  app/src/components/AssignmentBadge.tsx
  app/src/components/view/ranking/ImageList.tsx
  app/src/components/view/ranking/RankingListAll.tsx
  app/src/components/view/ranking/TopicTabs.tsx
Labels: Review effort [1-5]: 4

#80 スコア計算の修正とトーストをダイアログに集約した
  app/src/app/api/minio/route.ts
  app/src/app/camera/page.tsx
  app/src/components/view/PointDialog.tsx
  app/src/functions/scoreRegister.ts
  app/src/types/index.tsx
Labels: Review effort [1-5]: 4

#82 userページにrateを繋ぎ込み
  app/src/app/api/rate/user/[id]/route.ts
  app/src/app/user/page.tsx
  app/src/components/view/user/PlayerRankCard.tsx
  app/src/types/index.tsx
Labels: Review effort [1-5]: 4
